[project]
name = "data-proc-and-vis-subject-2a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "kagglehub>=1.0.1",
    "marimo>=0.23.8",
    "matplotlib>=3.10.9",
    "nbformat>=5.10.4",
    "pandas>=3.0.2",
    "scikit-learn>=1.8.0",
]

[tool.setuptools]
py-modules = ["cars"]
